### PR TITLE
group2_SurvivalAnalysis - final corrections

### PR DESCRIPTION
**Pull request by dariasmorodina**
Dear Johannes,
please accept these final adjustments (fixed lists, punctuation, some typos and citing). 
We hope that now everything will look perfect in our blog post.
Thank you very much.

Best regards,
Daria and Laura

### CODE REVIEW

**Comment by johaupt** [comment]
Looks good, thanks!

**Comment by dariasmorodina** [comment]
Dear Johannes,
thanks for updating.

Have you already updated the blog itself? Because I only see changes in git but not in blog.
Thanks, 
Daria

**Comment by johaupt** [comment]
Not yet, I'm waiting on other updates

**Comment by dariasmorodina** [comment]
Great, thanks a lot!

**Pull request merged**
