### PR TITLE
corrections

### PR DESCRIPTION
**Pull request by karolinagru**

### CODE REVIEW

**Comment by johaupt** [comment]
Please 
- delete .DS_Store files 
- fix merge conflict (see Moodle post for instructions)

**Comment by johaupt** [comment]
If you have trouble resolving the merge conflict, then consider committing your local changes and pulling the repository again. Then resolve the conflicts from the pull and maybe open a new pull request.

**Comment by johaupt** [comment]
Solved this one for you to move forward. 
Please check the post to confirm!

**Comment by karolinagru** [comment]
Thank you, it looks fine!

**Pull request merged**
